[package]
name = "carlo-help"
description = "A help utility for the simple interpreted programming language Carlo."
license = "MIT"
version = "1.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.carlotk]
path = "../../carlotk"
version = "1.0.0"