[package]
name = "carlo-latex"
description = "A LaTeX emitter for the simple interpreted programming language Carlo."
license = "MIT"
version = "0.2.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.carlotk]
path = "../../carlotk"
version = "0.12.0"